### ISSUE TITLE
Empty View does not seem to work properly.

### ISSUE THREAD

**Issue by gr3ger** [infinum/MjolnirRecyclerView#17]
Empty view is never shown, and it seems to disrupt headers aswell.
Test case:

If I only have a header, and no items in the lists, the entire screen is blank (neither header nor empty view can be seen)
```
        EventHeaderView header = EventHeaderView_.build(this);
        header.setEvent(eventId);
        mAdapter.addHeader(header, true);

        EmptyView empty = EmptyView_.build(this);
        empty.setText(getString(R.string.HOME_FEED_EMPTY_LIST_TEXT));
        recycler.setEmptyView(empty);
```

If only the empty view is set (no header, no extra items), it's again completely blank and nothing is showing.
```
        EventHeaderView header = EventHeaderView_.build(this);
        header.setEvent(eventId);
        //mAdapter.addHeader(header, true);

        EmptyView empty = EmptyView_.build(this);
        empty.setText(getString(R.string.HOME_FEED_EMPTY_LIST_TEXT));
        recycler.setEmptyView(empty);
```
If we only have the header and no empty view, it behaves as expected, only the header shows.
```
        EventHeaderView header = EventHeaderView_.build(this);
        header.setEvent(eventId);
        mAdapter.addHeader(header, true);

        EmptyView empty = EmptyView_.build(this);
        empty.setText(getString(R.string.HOME_FEED_EMPTY_LIST_TEXT));
        //recycler.setEmptyView(empty);
```
And to eliminate the possibility that my empty view is faulty, I tried this:
And the result is that the empty view shows properly as the header.
```
        EventHeaderView header = EventHeaderView_.build(this);
        header.setEvent(eventId);
        //mAdapter.addHeader(header, true);

        EmptyView empty = EmptyView_.build(this);
        empty.setText(getString(R.string.HOME_FEED_EMPTY_LIST_TEXT));
        mAdapter.addHeader(empty, true);
```

The expected behaviour when both header and empty views are set, and there are no items present, both should show (empty view below header).

Empty view should ONLY show when extra items are absent.

**Comment by zplesac** [comment]
@gr3ger thanks for the report, will investigate!

**Comment by zplesac** [comment]
@gr3ger Does your EmptyView has visibility set to GONE or INVISIBLE by default? If this is the case, empty view is not shown as we are only updating the visibility if the adapter is set to the RecyclerView. We can fix this with providing an extra method, with which you could declare do you want to show the empty view while adapter is not set.

For the expected behaviour, I don't agree that we should also show the header and footer views if there are no items in the adapter. We are trying to mimic the ListView's empty view behaviour, which shows only empty view in that case (header and footer are hidden).

**Comment by gr3ger** [comment]
Not at my work computer as of right now, so I can't double check. But I'll see if I can reliably replicate the issue (and check an extra time for visibility) and get back to you on that. It might even be some weird layout params thats the underlying problem. 

And as for the empty view only with the header gone, you might be right. Although it would be quite a nice feature to have if you imagine like a Facebook post without any comments, where the post itself is the header and the items are comments. In that scenario you would like to have the header persistent while the empty view is still visible. 

But as I said, I'll double check everything and get back to you.

**Comment by zplesac** [comment]
Closing this as there were not activity in last 26 days.
