### ISSUE TITLE
Footer/Header not removing properly

### ISSUE THREAD

**Issue by gr3ger** [infinum/MjolnirRecyclerView#25]
If you call addFooter(view, true), then later call removeFooter(), and again call addFooter(view, true) the old footer will still be there, I suspect it has something to do with the FooterViewHolder and HeaderViewHolder classes since they are only updated in onCreateViewHolder.

If you have a very small list, won't this pose a problem with the header/footer never actually updating their contents if you replace the view rather than modifying an existing one?

**Comment by zplesac** [comment]
Hi @gr3ger - this should be fixed with PR #28.

**Comment by zplesac** [comment]
Released to production.
