### ISSUE TITLE
Make hasHeader() protected

### ISSUE THREAD

**Issue by dmarusic35** [infinum/MjolnirRecyclerView#32]
There is private `hasHeader()` method in `MjolnirRecyclerAdapter`. It would be great if you can make it `protected`. It would be useful, for example, when you need to call notifyItemChanged method and you need to calculate the exact position of the item. In that case you'll need to know whether or not header is added.

**Comment by zplesac** [comment]
OK, not a problem. I'll also change _hasFooter()_ visibility to protected.

**Comment by zplesac** [comment]
Fixed in #33 and released in version 1.5.1
