### ISSUE TITLE
What about load more on scroll feature?

### ISSUE THREAD

**Issue by DASAR** [infinum/MjolnirRecyclerView#51]
- load more on scroll  (callback)
- optional 'loding' view at the end of list

**Comment by zplesac** [comment]
Hi @DASAR,

you can already use [OnNextPage](https://github.com/infinum/MjolnirRecyclerView/blob/master/mjolnirrecyclerview/src/main/java/co/infinum/mjolnirrecyclerview/MjolnirRecyclerAdapter.java#L46) callback listener, which is called when list is scrolled to the bottom.

Loading views are app specific feature (I.E, one app can have a loading view at the end of the list, second on the top, third in the middle...), so currently there are no plans to add support for this feature.

**Comment by DASAR** [comment]
Thanks
