### ISSUE TITLE
Using multiple view types in combination with header crashes

### ISSUE THREAD

**Issue by kjurkovic** [infinum/MjolnirRecyclerView#52]
If I use multiple view types such as
```
@Override
protected int getAdditionalItemViewType(int position) {
     return get(position).getType() == Usage.Type.LABEL ? YEAR : ITEM;
}
```
and I add header with `adapter.setHeader(View view);`, method `getAdditionalItemViewType` will receive wrong positions for items.

**Comment by zplesac** [comment]
Fixed in 2.1.0.
